config/routes.rb
Rails.application.routes.draw do
  root  'public#about'    #About (the game)

  get   'carousel/index'  #(play) the game
  get   'public/synopsis' #Synopsis
  get   'public/team'     #Team page
  get   'public/about'    #About (the game)
  get   'contacts/new'    #Contact us form page

  resources :contacts, only: [:new, :create]

  
  resource  :session,   only: [:create, :destroy]

  match 'auth/:provider/callback',  to: 'sessions#create', via: [:get, :post]
  match 'auth/failure',             to:  redirect('/'),    via: [:get, :post]
  match 'signout',                  to: 'sessions#destroy', as: 'signout', via: [:get, :post]

end

app/models/contact.rb
require 'mail_form'
require 'simple_form'

class Contact < MailForm::Base

  attribute :name,      validate: true
  attribute :email,     validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  captcha:  true

  # Declare the e-mail headers.
  # It accepts anything the mail method in ActionMailer accepts.
  def headers
    {
      subject:  "Message from a Carousel user.",
      to:       "CarouselFinal@gmail.com",
      from:     %("#{name}" <#{email}>)
    }
  end

end

app/models/inventory_item.rb
class InventoryItem < ActiveRecord::Base
  self.table_name   = :inventory_items
  self.primary_keys = :profile_id, :item_id
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/players_profile.rb
class PlayersProfile < ActiveRecord::Base

  belongs_to  :user

  has_many    :items, through: :inventory_items

end

app/models/user.rb
require 'pry'
class User < ActiveRecord::Base

  has_one :players_profile

  validates :age, numericality: { greater_than: 16 }

  class << self

    # class method
    def from_omniauth(auth)
      if (User.find_by(uid: auth.uid))
        user = User.find_by(uid: auth.uid)
      else
        user = User.create(
          provider:           auth.provider,
          uid:                auth.uid,
          name:               auth.info.name,
          oauth_token:        auth.credentials.token,
          oauth_expires_at:   Time.at(auth.credentials.expires_at),
          email:              auth.info.email,
          age:                auth.extra.raw_info.age_range.min.last,
          profile_photo_url:  auth.info.image
        )
      end
    end

  end

end
# End of class.

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # before_action :authenticated
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  helper_method :current_user
  
  def is_logged_in?
    !!current_user #this returns a boolean value rather than run the method and return the object.
  end
  helper_method :is_logged_in?

  def authenticated
    # render status: 400 if !is_logged_in?
    if (!is_logged_in?)
      # flash[:alert] = "Please sign in to play the demo."
      # redirect_to "/"
      redirect_to ("/"), flash: {alert: "Please sign in to play the demo."}
    end
  end
  helper_method :authenticated

end

app/controllers/carousel_controller.rb
class CarouselController < ApplicationController

  before_filter :authenticated        #from ApplicationController.rb
  before_filter :set_cache_buster

  def set_cache_buster
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"]        = "no-cache"
    response.headers["Expires"]       = "Fri, 01 Jan 1990 00:00:00 GMT"
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact          = Contact.new(params[:contact])
    @contact.request  = request

    if (@contact.deliver)
      redirect_to (new_contact_path), flash: {success: "Message delivered."}
    else
      render :new, flash: {failure: "Message could not be sent."}
    end
  end

end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user              = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to         carousel_index_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to         root_url
  end

  def create_failure
    redirect_to     root_url
    flash[:alert] = params[:message] # if using sinatra-flash or rack-flash
  end

end

app/controllers/users_controller.rb
# The entire UsersController has been commented-out since it is not in use at the present time.
# Since we do not perform any user management at present, this is not needed.
# How to re-enable: highlight the entire class then un-comment.

# class UsersController < ApplicationController
#   before_action :set_user, only: [:show, :edit, :update, :destroy]

#   # GET /users
#   # GET /users.json
#   def index
#     @users = User.all
#   end

#   # GET /users/1
#   # GET /users/1.json
#   def show
#   end

#   # GET /users/new
#   def new
#     @user = User.new
#   end

#   # GET /users/1/edit
#   def edit
#   end

#   # POST /users
#   # POST /users.json
#   def create
#     @user = User.new(user_params)

#     if (@user.save)
#       session[:user_id] = @user_id
#     end

#     # respond_to do |format|
#     #   if @user.save
#     #     format.html { redirect_to @user, notice: 'User was successfully created.' }
#     #     format.json { render :show, status: :created, location: @user }
#     #   else
#     #     format.html { render :new }
#     #     format.json { render json: @user.errors, status: :unprocessable_entity }
#     #   end
#     # end
#   end

#   # PATCH/PUT /users/1
#   # PATCH/PUT /users/1.json
#   def update
#     respond_to do |format|
#       if @user.update(user_params)
#         format.html { redirect_to @user, notice: 'User was successfully updated.' }
#         format.json { render :show, status: :ok, location: @user }
#       else
#         format.html { render :edit }
#         format.json { render json: @user.errors, status: :unprocessable_entity }
#       end
#     end
#   end

#   # DELETE /users/1
#   # DELETE /users/1.json
#   def destroy
#     @user.destroy
#     respond_to do |format|
#       format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
#       format.json { head :no_content }
#     end
#   end

#   private
#     # Use callbacks to share common setup or constraints between actions.
#     def set_user
#       @user = User.find(params[:id])
#     end

#     # Never trust parameters from the scary internet, only allow the white list through.
#     def user_params
#       params.require(:user)
#         .permit(
#           :provider,
#           :uid,
#           :name,
#           :oauth_token,
#           :oauth_expires_at,
#           :email,
#           :age,
#           :profile_photo_url
#         )
#     end

# end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def flash_class(level)
    case (level).to_sym
    when :notice  then  "alert-info"
    when :success then  "alert-success"
    when :error   then  "alert-danger"
    end
  end

end

app/helpers/carousel_helper.rb
module CarouselHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carousel/index.html.erb
<center><div id="background-container" content scroll="false">
  <img src="../images/gamebackground1.jpg" />

  <script src="/javascripts/phaser.js">                                  </script>
  <script src="/javascripts/box2d-plugin-full.js" type="text/javascript"></script>
  <script src="/javascripts/phaser-state-transition-plugin.min.js"      ></script>
  <script src="/javascripts/modules/factories/firefly.js">               </script>
  <script src="/javascripts/modules/factories/projectile.js">            </script>
  <script src="/javascripts/modules/factories/inventory.js">             </script>
  <script src="/javascripts/modules/states/Boot.js">                     </script>
  <script src="/javascripts/modules/states/Preload.js">                  </script>
  <script src="/javascripts/modules/states/Mainmenu.js">                 </script>
  <script src="/javascripts/modules/states/Oaktree.js">                  </script>
  <script src="/javascripts/modules/states/Stream.js">                   </script>
  <script src="/javascripts/modules/states/Minimenu.js">                 </script>
  <script src="/javascripts/modules/states/Minigame.js">                 </script>
  <script src="/javascripts/modules/states/EndDemo.js">                  </script>
  <script src="/javascripts/modules/CarouselGame.js">                    </script>

  <center><div id="gamecontainer"></div></center>

app/views/contacts/create.html.erb
<div>
    <% flash.each do |key, value| %>
        <div>
          <a href="#" data-dismiss="alert">×</a>
              <%= value %>
        </div>
    <% end %>
</div>

app/views/contacts/new.html.erb
<center>
    <div class="contact-div">
        <div class="contact-form">
            <%= render 'layouts/flash_messages' %>
            <br></br>
            <p>* Required</p>

            <%= simple_form_for (@contact), html: { class: 'form-horizontal' } do |f| %>
                <%= f.input :name,  required: true %>
                <%= f.input :email, required: true %>
                <%= f.input :message, as: :text, required: true %>

                <div class="hidden">
                    <%= f.input :nickname, hint: "Leave this field blank or else the message will be marked as spam." %>
                </div>

                <div>
                    </br>
                    <%= f.button :submit, "Send message", id: "btn btn-primary" %>
                </div>
            <% end %>
        </div>
    </div>
</center>

app/views/layouts/_flash_messages.html.erb
<div>
  <% flash.each do |key, value| %>
    <div class="alert <%= flash_class(key) %> fade in alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <%= value %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Carousel</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- <a class="navbar-brand" href="#">CAROUSEL</a> -->
                <div class='navbar-brand'>
                    <img src="/images/Carousellogo.png" />
                </div>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <%= link_to "About", public_about_path %>
                    </li>

                    <li>
                        <%= link_to "Synopsis", public_synopsis_path %>
                    </li>

                    <li>
                        <% if (current_user()) %>
                            <%= link_to "Play Game", carousel_index_path %>
                        <% else %>
                            <%= link_to "Play Game", "/auth/facebook", id: "sign_in" %>
                        <% end %>
                    </li>

                    <li>
                        <%= link_to "The Team", public_team_path %>
                    </li>

                    <li>
                        <%= link_to "Contact Us", contacts_new_path %>
                    </li>

                    <li id="user-widget">
                        <% if (current_user()) %>
                            <li>Welcome <strong><%= current_user.name %></strong>!</li>
                            <%= link_to "Sign out", signout_path, id: "sign_out" %>
                        <% end %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

  <%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :facebook %><br>
    <%= f.text_field :facebook %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Name</th>
      <th>Email</th>
      <th>Gender</th>
      <th>Bio</th>
      <th>Facebook</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.gender %></td>
        <td><%= user.bio %></td>
        <td><%= user.facebook %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/inventory.html.erb
<!DOCTYPE html>
<html>
    
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
        <script type="text/javascript" src="http://netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
        <link href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css"
        rel="stylesheet" type="text/css">
        <link href="http://pingendo.github.io/pingendo-bootstrap/themes/default/bootstrap.css"
        rel="stylesheet" type="text/css">
    </head>
    
    <body>
        <div class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-ex-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#"><span>Carousel: The Game</span></a>
                </div>
                <div class="collapse navbar-collapse" id="navbar-ex-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li class="active">
                            <a href="#">The Story</a>
                        </li>
                        <li>
                            <a href="#">Inventory</a>
                        </li>
                        <li>
                            <a href="#">Player Stats</a>
                        </li>
                        <li>
                            <a href="#">Log Out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="section">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="page-header">
                            <h1>Inventory</h1>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="btn-toolbar" role="toolbar">
                            <div class="btn-group">
                                <a type="button" class="btn btn-default">Inventory</a>
                                <a type="button" class="btn btn-default">Secrets</a>
                            </div>
                            <div class="btn-group"></div>
                            <div class="btn-group"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="section">
            <div class="container">
                <div class="row">
                    <div class="col-md-3">
                        <a><img src="http://pingendo.github.io/pingendo-bootstrap/assets/placeholder.png" class="img-responsive"></a>
                    </div>
                    <div class="col-md-3">
                        <a><img src="http://pingendo.github.io/pingendo-bootstrap/assets/placeholder.png" class="img-responsive"></a>
                    </div>
                    <div class="col-md-3">
                        <a><img src="http://pingendo.github.io/pingendo-bootstrap/assets/placeholder.png" class="img-responsive"></a>
                    </div>
                    <div class="col-md-3">
                        <a><img src="http://pingendo.github.io/pingendo-bootstrap/assets/placeholder.png" class="img-responsive"></a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3">
                        <a><img src="http://pingendo.github.io/pingendo-bootstrap/assets/placeholder.png" class="img-responsive"></a>
                    </div>
                    <div class="col-md-3">
                        <a><img src="http://pingendo.github.io/pingendo-bootstrap/assets/placeholder.png" class="img-responsive"></a>
                    </div>
                    <div class="col-md-3">
                        <a><img src="http://pingendo.github.io/pingendo-bootstrap/assets/placeholder.png" class="img-responsive"></a>
                    </div>
                    <div class="col-md-3">
                        <a><img src="http://pingendo.github.io/pingendo-bootstrap/assets/placeholder.png" class="img-responsive"></a>
                    </div>
                </div>
            </div>
        </div>
        <footer class="section section-primary">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6">
                        <h1>Footer header</h1>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisici elit,
                            <br>sed eiusmod tempor incidunt ut labore et dolore magna aliqua.
                            <br>Ut enim ad minim veniam, quis nostrud</p>
                    </div>
                    <div class="col-sm-6">
                        <p class="text-info text-right">
                            <br>
                            <br>
                        </p>
                        <div class="row">
                            <div class="col-md-12 hidden-lg hidden-md hidden-sm text-left">
                                <a href="#"><i class="fa fa-3x fa-fw fa-instagram text-inverse"></i></a>
                                <a href="#"><i class="fa fa-3x fa-fw fa-twitter text-inverse"></i></a>
                                <a href="#"><i class="fa fa-3x fa-fw fa-facebook text-inverse"></i></a>
                                <a href="#"><i class="fa fa-3x fa-fw fa-github text-inverse"></i></a>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12 hidden-xs text-right">
                                <a href="#"><i class="fa fa-3x fa-fw fa-instagram text-inverse"></i></a>
                                <a href="#"><i class="fa fa-3x fa-fw fa-twitter text-inverse"></i></a>
                                <a href="#"><i class="fa fa-3x fa-fw fa-facebook text-inverse"></i></a>
                                <a href="#"><i class="fa fa-3x fa-fw fa-github text-inverse"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </body>

</html>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/playerstats.html.erb
<!DOCTYPE html>
<html>
    
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
        <script type="text/javascript" src="http://netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
        <link href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css"
        rel="stylesheet" type="text/css">
        <link href="http://pingendo.github.io/pingendo-bootstrap/themes/default/bootstrap.css"
        rel="stylesheet" type="text/css">
    </head>
    
    <body>
        <div class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-ex-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#"><span>Carousel: The Game</span></a>
                </div>
                <div class="collapse navbar-collapse" id="navbar-ex-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li class="active">
                            <a href="#">The Story</a>
                        </li>
                        <li>
                            <a href="#">Inventory</a>
                        </li>
                        <li>
                            <a href="#">Player Stats</a>
                        </li>
                        <li>
                            <a href="#">Log Out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="section">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="page-header">
                            <h1>Player Stats</h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="section">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <p>Hello, [username]!
                            <br>
                            <br>Current Chapter: [integer] (continue?) &lt;--- link to game
                            <br>Current Story Path: [Path Name]
                            <br>
                            <br>Death Count: You've died _______ &nbsp;times.
                            <br>
                            <br>TOP SCORES
                            <br>a) Firefly Chase:
                            <br>
                            <br>Number of Unlocked Secrets: [integer]
                            <br>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <footer class="section section-primary">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6">
                        <h1>Footer header</h1>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisici elit,
                            <br>sed eiusmod tempor incidunt ut labore et dolore magna aliqua.
                            <br>Ut enim ad minim veniam, quis nostrud</p>
                    </div>
                    <div class="col-sm-6">
                        <p class="text-info text-right">
                            <br>
                            <br>
                        </p>
                        <div class="row">
                            <div class="col-md-12 hidden-lg hidden-md hidden-sm text-left">
                                <a href="#"><i class="fa fa-3x fa-fw fa-instagram text-inverse"></i></a>
                                <a href="#"><i class="fa fa-3x fa-fw fa-twitter text-inverse"></i></a>
                                <a href="#"><i class="fa fa-3x fa-fw fa-facebook text-inverse"></i></a>
                                <a href="#"><i class="fa fa-3x fa-fw fa-github text-inverse"></i></a>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12 hidden-xs text-right">
                                <a href="#"><i class="fa fa-3x fa-fw fa-instagram text-inverse"></i></a>
                                <a href="#"><i class="fa fa-3x fa-fw fa-twitter text-inverse"></i></a>
                                <a href="#"><i class="fa fa-3x fa-fw fa-facebook text-inverse"></i></a>
                                <a href="#"><i class="fa fa-3x fa-fw fa-github text-inverse"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </body>

</html>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @user.gender %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @user.bio %>
</p>

<p>
  <strong>Facebook:</strong>
  <%= @user.facebook %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>